### ISSUE TITLE
File format - need a standard

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/biovalidator#12]
In the app (and in biovalidator) we use enums to represent the file formats.

Here is the spec: [openapi.json](https://github.com/intermine/intermine_configurator/blob/master/openapi.json#L905)

This is the Java representation of that: [DataFile.java](https://github.com/intermine/intermine_configurator/blob/master/src/main/java/io/swagger/model/DataFile.java#L30)

This is fragile. I guess I see this as a place for future bugs! Right now we are okay with just the handful of file types we have. But in the future?

Ideally we would have a standard that we would use. I don't think there is any "good" answer. But we can mitigate the danger by:

* put a comment in configurator to be sure to check valid types in biovalidator
* Have biovalidator be very permissive with the file type names, e.g. case insensitive, accept "GFF" and "GFF3"

**Comment by yochannah** [comment]
Popping in with a wee comment: it would be nice whatever this standard is ends up readable in any language, e.g. a json config file might be nice. I don't know if this is feasible and it's not the end of the world if it doesn't happen.
