### ISSUE TITLE
Error message suppression strategy?

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/biovalidator#14]
(Just because I am thinking about error messages, and I have NOT tested this.)

What happens when the GFF file has the wrong number of columns. Are we going to get an error message for each bad row? It could be that we have some validation rules that are only enforced once. e.g. check for number of columns each row. but on fail, don't check again.

Ignore if you've handled this!! :)

**Comment by deepakkumar96** [comment]
I'm not sure having wrong number of columns in a GFF file is valid or
invalid(I guess it should be invalid),
1. In case of Strict validation, shouldn't validator stop and report error
if having wrong numbers of column is invalid?
2. In case of permissive, should it allow?

Deepak,

**Comment by julie-sullivan** [comment]
1. Yes! 
2. Good question. I think we need @rachellyne's help on this one! :)

Well, let's take another example. FASTA and invalid characters. What if one line is `1111111111`. Would you have an error message for every character? 

**OPTION 1**
```
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
Invalid character found on line 12 - 1
```
**OPTION 2**
```
Invalid character found - "1"
```

Option 1 is better but what if there are 100s of them? Is *that* our biggest concern then? Maybe after N number of messages, suppress?

**Comment by deepakkumar96** [comment]
1. Currently, Fasta validator will stop as soon as it gets first error so
OPTION 2 will be the output,
but you configure validator to disable stopAtFirstError rule using
ValidatorBuilder, this will validate whole file which might work for
smaller file but can't work for bigger files.

Example of disabling stop at first error rule :
     Validator validator = ValidatorBuilder.withFile("path", "fasta-protein"
)
        .disableErrors()
        .disableStopAtFirstError()
        .build();

2. But if we want output like OPTION 1, then I may have add a method like
stopAfterNErrors(10).

what do you think?

Deepak,

**Comment by julie-sullivan** [comment]
this is fine as is. maybe mention this is something that can be optimised in the future.
