### ISSUE TITLE
Make rules more visible. 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/biovalidator#18]
I see the rules here, which is great:

https://github.com/intermine/biovalidator/blob/master/src/main/java/org/intermine/biovalidator/validator/fasta/FastaValidator.java#L42

But it's a bit hidden. Can we make it more prominent somehow? We want this available by the command line and in github.

**Comment by deepakkumar96** [comment]
Yes sure!

**Comment by julie-sullivan** [comment]
they are on the wiki now.
