### ISSUE TITLE
Make error messages very verbose.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/biovalidator#19]
We want to give the user enough information to fix the problem.

This goes for all error messages but specifically `file not found`. Update this error message to include the path that was tried.

**Comment by deepakkumar96** [comment]
Ok, I'm changing the 'file not found' message to include path too!

**Comment by julie-sullivan** [comment]
Just thinking out loud here. Do we want to throw an exception there? 

Another option would be to catch that exception and return the correct error message. 

We don't want fatal errors in our library, I don't think?

**Comment by deepakkumar96** [comment]
I thought if the library is not able to find the file, then its not a
validation error, and that is why I throw an error!

**Comment by deepakkumar96** [comment]
Sorry, which exception you were referring to?  FileNotFoundException or
something else?

**Comment by julie-sullivan** [comment]
There was an exception for other things as well. For having the wrong file type, for example.

I can add a bunch of catch statements when using your library, but I am going to be doing the same thing for each -- returning the error message to the user.

**Comment by julie-sullivan** [comment]
this is done, the file path is given in the error message.
