### ISSUE TITLE
Only want error messages, don't want exceptions

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/biovalidator#25]
Again, when I didn't provide the filetype, I got an illegal argument exception. Instead, I would like an informative error message "filetype required: FASTA or GFF3".

What are fatal exceptions for? They are to stop the process because there is simply no point in going on. Something very bad has happened. In our case, that doesn't really apply. Does that make sense? Something bad has happened (e.g. no filetype), but we don't need to kill the process, we only want to stop what we are doing and return the relevant information to the user.

Exceptions in Java also let you do custom actions for certain exceptions, e.g. close database connections, write to the log etc. We don't have those in our case, we always only ever want to return the error message to the user.

I think your error handling is correct however, it makes using the library more difficult. Look at my code, I have to catch a bunch of exceptions, then check for NULL then check the error messages. Very messy! It's not maintainable -- later on you may change the exceptions, people will forget what exceptions are thrown etc. And I am finding it really hard to write my unit tests. 

This is a specific library to do a specific job. These fatal errors don't help do that job. Because this library is part of a big application, your library should catch the errors, and return an informative error message to the user so they can act on them. 

Thoughts?

**Comment by deepakkumar96** [comment]
Hi,
As you said, we Only want error messages, not exceptions, So I'm going to
change the signature of all the methods of ValidatorHelper class,
returning only ValidationResult(with some error message) even if there is
some non-validation error like "file not found"!

Thanks,
Deepak.

**Comment by julie-sullivan** [comment]
working as expected! :)
