### ISSUE TITLE
extractSequenceIdFromHeader() could be more readable

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/biovalidator#6]
https://github.com/intermine/biovalidator/blob/3b5e73c7140897e7ec5c0c5c95d08fa0734c773b/src/main/java/org/intermine/biovalidator/validator/fasta/FastaValidator.java#L147

Can you add some comments to `extractSequenceIdFromHeader()`? Specifically because I am wondering why `split()` wouldn't be appropriate (I actually don't know!). but in looking at the function it's a little hard to understand what's going on.

Thanks!

**Comment by deepakkumar96** [comment]
Yes, I could have added a comment to describe what's going on,
So basically that method extracts seq.id from the beginning to the first
whitespace.
I thought as fasta files are generated from databases, and there are lots
of possible value for whitespace
<https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isWhitespace(char)>,
so I decided to manually iterate over header first space, instead of split.

**Comment by deepakkumar96** [comment]
Hello,
Should I make changes to the extractSequenceIdFromHeader() ?

Deepak,
Thanks!

**Comment by julie-sullivan** [comment]
Yes please! If you can make it more obvious what's going on, that would be great! :) The idea is that we might have to add "exceptions" to the rule, so I need it to be SUPER obvious how to manipulate that function. 

1. I don't like `break` -- might be personal preference!!
2. only comment the lines that are not immediately obvious. 
3. i love that you used the ternary operator! :) But it can lead to loonnngg lines that take a few moments to digest. A comment would be good here! Keeps me from having to guess.

**Comment by deepakkumar96** [comment]
Okay, thanks for the review these things will make me learn more,
And I accept that 'break' and 'continue' statements makes code harder to
read and should be avoided!

Thanks,
Deepak

**Comment by julie-sullivan** [comment]
> there are lots of possible value for whitespace <https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isWhitespace(char)>,

You can use regex for this too, which `split()` accepts:
https://docs.oracle.com/javase/6/docs/api/java/util/regex/Pattern.html

**Comment by deepakkumar96** [comment]
How about StringUtils.split()
<https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/StringUtils.html#split-java.lang.String->
(from Apache common lang, as I've already included as a dependency), which
basically split on Character.isWhitespace().

**Comment by julie-sullivan** [comment]
much easier to read now, thanks! nice job.
